# The URL the site will be built for
base_url = "https://tinywren.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola-custom-minimal"
title  = "Tiny Wren"
description = "tinywren.dev by Andy Shearer"

generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

[extra]
# Put all your custom variables here

